"""Browser integration tests. Install Python Playwright separately; no app dependencies.
Defaults to an inline, opaque-origin harness; --url exercises a locally served build.
The inline harness uses an in-memory Storage fixture, not persistent browser storage.
"""
from pathlib import Path
import argparse, base64, io, json, os, time, zipfile
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--url', default=None)
parser.add_argument('--chromium', default=os.getenv('CHROMIUM', '/usr/bin/chromium'))
args = parser.parse_args()
checks = []
def check(name, condition, detail=None):
    if not condition:
        raise AssertionError(f'{name}: {detail}')
    checks.append({'name': name, 'passed': True, 'detail': detail})
    print('PASS', name, flush=True)

with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=args.chromium, headless=True, args=['--no-sandbox'])
    page = browser.new_page(viewport={'width':1536, 'height':1240}, device_scale_factor=1)
    launch_mock = "Object.defineProperty(window,'launchQueue',{configurable:true,value:{setConsumer:consumer=>window.testFileLaunch=consumer}});"
    page.add_init_script(launch_mock)
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    if args.url:
        page.goto(args.url, wait_until='networkidle')
    else:
        storage = '''<script>(()=>{const m=new Map();Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),clear:()=>m.clear(),key:i=>[...m.keys()][i]??null,get length(){return m.size}}});})();</script>'''
        html = (ROOT/'dist/index.html').read_text()
        page.set_content(html.replace('<head>', '<head><script>'+launch_mock+'</script>'+storage, 1), wait_until='networkidle')
    page.wait_for_function('window.gridline && window.gridline.ready', timeout=45000)
    page.wait_for_timeout(300)
    backend = page.evaluate('({backend:gridline.renderer.backend,reason:gridline.renderer.fallbackReason})')
    check('Standalone app boots without an uncaught exception', not errors, errors)
    check('Startup defaults to the file popup with reopen disabled', page.locator('#reopen-last').is_visible() and not page.locator('#reopen-last').is_checked() and page.evaluate('gridline.sheet.cells.size===0'))
    page.locator('#reopen-last').check()
    check('Reopen preference can be enabled', page.evaluate('localStorage.getItem("gridline.reopen-last.v1")') == 'true')
    page.locator('#reopen-last').uncheck()
    page.locator('#dialog [data-action="sample"]').click()
    page.locator('#confirm-action').click()
    check('Demo total is calculated', page.evaluate('gridline.workbook.value(gridline.sheet,5,1)') == 2187000)
    check('Demo has three sheets and two chart overlays', page.locator('.sheet-tab').count()==3 and page.locator('.chart-card').count()==2)
    (ROOT/'docs').mkdir(exist_ok=True)
    page.screenshot(path=str(ROOT/'docs/preview.png'), full_page=True)
    def goto(ref):
        page.locator('#name-box').fill(ref)
        page.locator('#name-box').press('Enter')
    def val(r,c):
        return page.evaluate('p=>gridline.workbook.value(gridline.sheet,p[0],p[1])',[r,c])
    goto('D12')
    page.keyboard.type('200000')
    page.keyboard.press('Enter')
    check('Typing commits a real numeric cell', val(11,3)==200000, val(11,3))
    check('Editing recalculates dependent total', val(5,1)==2219000, val(5,1))
    page.keyboard.press('Control+z')
    check('Keyboard undo restores both input and calculated total', val(11,3)==168000 and val(5,1)==2187000)
    page.keyboard.press('Control+y')
    check('Keyboard redo reapplies the transaction', val(11,3)==200000)
    page.keyboard.press('Control+z')
    goto('G13')
    page.locator('#formula-input').fill('=SUM(D13:F13)+1000')
    page.locator('#formula-input').press('Enter')
    check('Formula bar parses, commits, and calculates', val(12,6)==409000, val(12,6))
    page.keyboard.press('Control+z')
    page.locator('[data-action="add-sheet"]').click()
    check('New worksheet command creates a sheet', page.evaluate('gridline.workbook.sheets.length')==4)
    goto('A1')
    # Native paste event path, including multiline data and formulas.
    page.evaluate('''()=>{const d=new DataTransfer();d.setData('text/plain','Item\\tUnits\\tPrice\\tRevenue\\nAlpha\\t2\\t10\\t=B2*C2\\nBeta\\t3\\t20\\t=B3*C3');document.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));}''')
    check('Clipboard paste event enters a rectangular range', val(1,0)=='Alpha' and val(2,1)==3)
    check('Pasted formulas calculate', val(1,3)==20 and val(2,3)==60)
    goto('D2:D6')
    page.keyboard.press('Control+d')
    check('Fill-down shifts relative references', page.evaluate('gridline.sheet.raw(5,3)')=='=B6*C6')
    goto('B2:C3')
    page.locator('#ribbon [data-action="copy"]').click()
    goto('F2')
    page.locator('#ribbon [data-action="paste"]').click()
    check('Internal clipboard fallback preserves rectangular values', val(1,5)==2 and val(2,6)==20)
    goto('D2')
    page.locator('#ribbon [data-action="copy"]').click()
    goto('H2')
    page.locator('#ribbon [data-action="paste"]').click()
    check('Internal formula copy translates references', page.evaluate('gridline.sheet.raw(1,7)')=='=F2*G2' and val(1,7)==20)
    goto('A1:D1')
    page.locator('[data-action="bold"]').click()
    check('Ribbon formatting applies to the selection', page.evaluate('[0,1,2,3].every(c=>gridline.sheet.get(0,c).style.bold)'))
    page.locator('.sheet-tab.selected').dblclick()
    page.locator('#sheet-name-input').fill('Browser test')
    page.locator('#sheet-rename-apply').click()
    check('Worksheet rename dialog updates model and tab', page.evaluate('gridline.sheet.name')=='Browser test' and page.locator('.sheet-tab.selected').inner_text()=='Browser test')
    goto('B2')
    page.locator('[data-tab="View"]').click()
    page.locator('[data-action="freeze"]').click()
    check('Freeze panes uses active row and column', page.evaluate('gridline.sheet.freezeRows===1 && gridline.sheet.freezeCols===1'))
    page.locator('[data-tab="Review"]').click()
    page.locator('[data-action="add-note"]').click()
    page.locator('#note-text').fill('Browser test note: local-only annotation.')
    page.locator('#note-save').click()
    check('Cell notes persist into the model and panel', page.evaluate('gridline.sheet.get(1,1).note')=='Browser test note: local-only annotation.' and page.locator('.note-card').count()==1)
    page.locator('[data-action="close-panel"]').click()
    page.locator('[data-tab="Home"]').click()
    goto('A1:D3')
    page.locator('[data-tab="Data"]').click()
    page.locator('[data-action="sort-desc"]').click()
    check('Sorting preserves header and reorders data rows', val(0,0)=='Item' and val(1,0)=='Beta' and val(2,0)=='Alpha')
    goto('A1:D3')
    page.locator('[data-action="filter"]').click()
    page.locator('.filter-values label').filter(has_text='Alpha').locator('input').uncheck()
    page.locator('#filter-apply').click()
    check('Value filters hide nonmatching rows', page.evaluate('gridline.sheet.hiddenRows.size')==1)
    page.locator('[data-action="clear-filter"]').click()
    check('Clear filters restores visibility', page.evaluate('gridline.sheet.hiddenRows.size')==0)
    page.locator('[data-tab="Home"]').click()
    page.locator('[data-action="find"]').click()
    page.locator('#find-query').fill('Alpha')
    page.locator('#replace-query').fill('Gamma')
    page.locator('#replace-all').click()
    check('Find and replace edits matching cells', val(2,0)=='Gamma')
    page.locator('[data-action="close-panel"]').click()
    # Verify actual XML parsing, all formulas, styles, dimensions and workbook names.
    roundtrip = page.evaluate('''async()=>{const original=Gridline.createSampleWorkbook();const bytes=await Gridline.exportXLSX(original);const {workbook:restored,warnings}=await Gridline.importXLSX(bytes,'Roundtrip');let mismatches=[];for(let i=0;i<original.sheets.length;i++){const a=original.sheets[i],b=restored.sheets[i];for(const [key,cell]of a.cells){if(!cell.raw)continue;const[r,c]=key.split(',').map(Number);const av=original.value(a,r,c),bv=restored.value(b,r,c);if(String(av)!==String(bv))mismatches.push(a.name+'!'+key+': '+av+' != '+bv);}}return {bytes:bytes.length,sheets:restored.sheets.length,mismatches,mergeCount:restored.sheets[0].merges.length,originalMerges:original.sheets[0].merges.length,freeze:restored.sheets[1].freezeRows,name:restored.names.COST_RATIO,style:restored.sheets[0].get(1,1).style,columns:restored.sheets[0].colWidths.size,warnings};}''')
    check('XLSX export/import round-trip preserves calculated values', roundtrip['sheets']==3 and not roundtrip['mismatches'], roundtrip)
    check('XLSX round-trip preserves basic workbook structures', roundtrip['mergeCount']==roundtrip['originalMerges'] and roundtrip['freeze']==1 and roundtrip['name'] and roundtrip['columns']>0)
    custom_dates = page.evaluate("""async()=>{const w=new Gridline.Workbook(),s=w.activeSheet;const formats=['mm-dd-yy','[$-409]m/d/yyyy','m/d/yy h:mm','hh:mm:ss'];formats.forEach((format,c)=>w.setCell(s,0,c,{raw:'45292.5625',style:{format}}));const imported=(await Gridline.importXLSX(await Gridline.exportXLSX(w))).workbook;return formats.map((_,c)=>imported.display(imported.activeSheet,0,c));}""")
    check('Excel custom date and time formats apply automatically on import', custom_dates == ['01-01-24','1/1/2024','1/1/24 13:30','13:30:00'], custom_dates)
    encoded = page.evaluate("async()=>btoa(Array.from(await Gridline.exportXLSX(Gridline.createSampleWorkbook()),v=>String.fromCharCode(v)).join(''))")
    original_zip = zipfile.ZipFile(io.BytesIO(base64.b64decode(encoded)))
    def repack(date1904=False):
        output = io.BytesIO()
        with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as z:
            for name in original_zip.namelist():
                data = original_zip.read(name)
                if date1904 and name=='xl/workbook.xml':
                    data=data.replace(b'<sheets>',b'<workbookPr date1904="1"/><sheets>')
                z.writestr(name, data)
        return base64.b64encode(output.getvalue()).decode()
    compressed = page.evaluate("async b=>{const {workbook:w}=await Gridline.importXLSX(Uint8Array.from(atob(b),c=>c.charCodeAt(0)));return w.value(w.sheets[0],5,1);}", repack())
    check('Native DEFLATE decompression imports a compressed XLSX', compressed==2187000)
    rejection = page.evaluate("async b=>{try{await Gridline.importXLSX(Uint8Array.from(atob(b),c=>c.charCodeAt(0)));return '';}catch(e){return e.message;}}", repack(True))
    check('Unsupported 1904 date-system files are rejected explicitly', '1904' in rejection)
    page.wait_for_timeout(800)
    check('Autosave writes a restorable workbook snapshot to Storage interface', page.evaluate("Gridline.Workbook.fromJSON(JSON.parse(localStorage.getItem('gridline.workbook.v1'))).sheets.length") == 4)
    page.locator('[data-action="performance"]').click()
    start = time.perf_counter()
    page.locator('#perf-test').click()
    elapsed = (time.perf_counter()-start)*1000
    check('Stress sheet creates 80,008 sparse cells', page.evaluate('gridline.sheet.cells.size')==80008, {'wall_ms':round(elapsed,2)})
    page.locator('[data-action="close-panel"]').click()
    goto('D10001')
    page.wait_for_timeout(200)
    check('Virtualized scrolling reaches row 10,001 with correct formulas', val(10000,3)==50 and val(10000,7)==5, {'revenue':val(10000,3),'contribution':val(10000,7)})
    metrics = page.evaluate('({visibleCells:gridline.renderer.visibleCellCount,lastFrameCPUms:gridline.renderer.lastFrameMs,storedCells:gridline.sheet.cells.size,active:gridline.active})')
    check('Stress view renders only its viewport', metrics['visibleCells']<2000, metrics)
    page.locator('[data-action="theme"]').click()
    check('Theme toggle updates renderer state', page.evaluate('gridline.renderer.dark') is True)
    page.locator('[data-action="zoom-in"]').click()
    check('Zoom command updates the viewport transform', abs(page.evaluate('gridline.renderer.zoom')-1.1)<1e-9)
    # Formatting must survive real UI editing and both workbook formats.
    page.evaluate('gridline.setWorkbook(new Gridline.Workbook()); gridline.renderer.setZoom(1)')
    host = page.locator('#grid-host').bounding_box()
    point = page.evaluate('gridline.renderer.cellRect(0,1)')
    page.mouse.click(host['x'] + point['x'] + point['w']/2, host['y'] + 12, button='right')
    page.locator('#context-menu [data-action="format-cells"]').click()
    page.locator('#format-category').select_option('date')
    check('Date format choices are visible as a list', page.locator('#format-pattern').evaluate('(el)=>el.clientHeight > 100 && el.options.length > 5'))
    page.locator('#format-pattern').select_option('yyyy-mm-dd')
    page.locator('#format-apply').click()
    check('Right-click column formatting creates one sparse default', page.evaluate('gridline.sheet.colStyles.size === 1 && gridline.sheet.cells.size === 0 && gridline.sheet.colStyles.has(1)'))
    goto('B1000')
    page.keyboard.type('2026-09-08')
    page.keyboard.press('Enter')
    goto('B1000')
    check('Date entry uses a serial internally and a readable formula bar', isinstance(val(999,1),(int,float)) and page.locator('#formula-input').input_value() == '2026-09-08', page.evaluate('({value:gridline.workbook.value(gridline.sheet,999,1),style:gridline.sheet.style(999,1),input:document.querySelector("#formula-input").value})'))
    before = val(999,1)
    page.keyboard.press('F2')
    check('Date editor shows a readable date', page.locator('#cell-editor').input_value() == '2026-09-08')
    page.keyboard.press('Enter')
    check('Unchanged date editing preserves the numeric value', val(999,1) == before)
    goto('B1000')
    page.keyboard.press('F2')
    page.locator('#cell-editor').fill('2025-02-29')
    page.keyboard.press('Enter')
    check('Invalid dates keep the editor open and the original value', page.evaluate('gridline.editing') and val(999,1) == before)
    page.keyboard.press('Escape')
    page.keyboard.press('Control+1')
    page.locator('#format-category').select_option('currency')
    page.locator('#format-currency').select_option('EUR')
    page.locator('#format-decimals').fill('2')
    page.locator('#format-apply').click()
    check('Keyboard format dialog changes only presentation', val(999,1) == before and page.evaluate('gridline.workbook.display(gridline.sheet,999,1).startsWith("€")'))
    page.evaluate('gridline.workbook.undo()')
    page.keyboard.press('Control+1')
    page.locator('#format-category').select_option('number')
    page.locator('#dialog [data-action="close-dialog"]').last.click()
    check('Cancel discards format changes', page.evaluate('gridline.workbook.display(gridline.sheet,999,1)') == '2026-09-08')
    goto('A1')
    point = page.evaluate('gridline.renderer.cellRect(2,0)')
    page.mouse.click(host['x'] + 12, host['y'] + point['y'] + point['h']/2, button='right')
    page.locator('#context-menu [data-action="format-cells"]').click()
    page.locator('#format-category').select_option('percent')
    page.locator('#format-decimals').fill('1')
    page.locator('#format-apply').click()
    check('Right-click row formatting creates a sparse row default', page.evaluate('gridline.sheet.rowStyles.has(2) && gridline.sheet.cells.size === 1'))
    roundtrip = page.evaluate("""async () => {
      const w = gridline.workbook, s = gridline.sheet;
      w.setRaw(s,2,4,'0.125');
      w.applyStyle(s,{r1:0,r2:1048575,c1:3,c2:3},{format:'time',pattern:'h:mm AM/PM'});
      w.setRaw(s,0,3,'13:30');
      w.applyStyle(s,{r1:0,r2:1048575,c1:5,c2:5},{format:'currency',currency:'CAD',decimals:3,grouping:false});
      w.setRaw(s,0,5,'1234.567');
      w.applyStyle(s,{r1:1,r2:1,c1:5,c2:5},{format:'general'}); w.setRaw(s,1,5,'42');
      w.applyStyle(s,{r1:3,r2:3,c1:0,c2:16383},{format:'general'}); w.setRaw(s,3,5,'43');
      const expected = [[999,1],[2,4],[0,3],[0,5],[1,5],[3,5]].map(([r,c])=>w.display(s,r,c));
      gridline.persist();
      const native = Gridline.Workbook.fromJSON(JSON.parse(localStorage.getItem('gridline.workbook.v1')));
      const imported = (await Gridline.importXLSX(await Gridline.exportXLSX(w))).workbook;
      const results = [native,imported].map(book => {
        const sheet = book.activeSheet, display = [[999,1],[2,4],[0,3],[0,5],[1,5],[3,5]].map(([r,c])=>book.display(sheet,r,c));
        book.setRaw(sheet,5000,1,'2027-01-02'); book.setRaw(sheet,5000,3,'09:15'); book.setRaw(sheet,5000,5,'10.5');
        return {display, future:[book.display(sheet,5000,1),book.display(sheet,5000,3),book.display(sheet,5000,5)], size:sheet.cells.size};
      });
      gridline.setWorkbook(imported);
      return {expected,results};
    }""")
    check('Native save and XLSX preserve date/time/currency/row formats', all(r['display'] == roundtrip['expected'] for r in roundtrip['results']), roundtrip)
    check('Loaded column defaults apply to future entries without expanding the sheet', all(r['future'] == ['2027-01-02','9:15 AM','CA$10.500'] and r['size'] == 9 for r in roundtrip['results']), roundtrip)
    goto('F1')
    page.keyboard.press('Control+1')
    page.screenshot(path='/tmp/gridline-format-dialog.png', full_page=True)
    page.locator('#dialog [data-action="close-dialog"]').last.click()
    security = page.evaluate("""async () => {
      const payload = '0"><img src="data:image/png;base64,AA==" onerror="window.__formatInjection=1"><input value="0';
      const original = gridline.workbook, rejected = [];
      for (const location of ['cells','rowStyles','colStyles']) {
        const data = new Gridline.Workbook().toJSON(), style = {format:'number',decimals:payload};
        data.sheets[0][location] = location === 'cells' ? [['0,0',{raw:'',style}]] : [[0,style]];
        try { await gridline.openFile(new File([JSON.stringify(data)], 'untrusted.gridline')); rejected.push(false); }
        catch (error) { rejected.push(error.message.includes('Invalid decimal places')); }
      }
      const preserved = gridline.workbook === original;
      // Bypass import validation to exercise safe rendering independently.
      const workbook = new Gridline.Workbook();
      workbook.setCell(workbook.activeSheet,0,0,{raw:'',style:{format:'number',decimals:payload}});
      gridline.setWorkbook(workbook); gridline.showFormatCells();
      await new Promise(resolve => setTimeout(resolve,100));
      const safe = !window.__formatInjection && !document.querySelector('#format-options img') && document.querySelector('#format-decimals').value === '2';
      gridline.closeDialog();
      return {rejected,preserved,safe};
    }""")
    check('Malicious decimal settings are rejected from cell, row, and column file styles', all(security['rejected']) and security['preserved'], security)
    check('Format dialog treats hostile precision as data even if import validation is bypassed', security['safe'], security)
    page.evaluate("""() => { const w=new Gridline.Workbook(); gridline.setWorkbook(w); [['Group','Score'],['A','1'],['A','3'],['B','2']].forEach((row,r)=>row.forEach((v,c)=>w.setRaw(w.activeSheet,r,c,v))); }""")
    goto('A1:B4')
    page.evaluate("gridline.showSort()")
    page.locator('#sort-add').click()
    page.locator('.sort-level').nth(1).locator('select').nth(0).select_option('1')
    page.locator('.sort-level').nth(1).locator('select').nth(1).select_option('desc')
    page.locator('#sort-apply').click()
    check('Custom sort applies secondary descending level', val(1,1)==3)
    goto('B1:B1048576')
    page.evaluate("gridline.run('hide-columns')")
    check('Hide columns removes column from layout', page.evaluate('gridline.renderer.cols.size(1)')==0)
    page.evaluate("gridline.run('unhide-all-columns')")
    check('Unhide restores column width', page.evaluate('gridline.renderer.cols.size(1)')==106)
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,0,3,'A'); gridline.workbook.setRaw(gridline.sheet,0,4,'A')")
    goto('D1:D1048576')
    page.evaluate('gridline.showFind()')
    page.locator('#find-query').fill('A')
    page.locator('#find-next').click()
    page.locator('#replace-query').fill('Changed')
    page.locator('#replace-all').click()
    check('Column replacement keeps its scope after navigating a match', val(0,3)=='Changed' and val(0,4)=='A')
    page.evaluate("gridline.closePanel();gridline.workbook.setRaw(gridline.sheet,0,5,'001,hello');gridline.workbook.setRaw(gridline.sheet,1,5,'002,world')")
    goto('F1:F2')
    page.evaluate('gridline.showTextToColumns()')
    page.locator('#split-format').select_option('text')
    page.locator('#split-apply').click()
    check('Text to Columns splits rows and preserves leading zeros in Text mode', val(0,5)=='001' and val(1,6)=='world')
    page.evaluate('gridline.workbook.undo()')
    check('Text to Columns undoes as one operation', val(0,5)=='001,hello' and val(1,6) is None)
    goto('F1:F2')
    page.evaluate('gridline.showTextToColumns()')
    page.locator('#split-destination').fill('D1')
    page.locator('#split-apply').click()
    check('Text to Columns asks before replacing neighboring data', page.locator('#confirm-action').count()==1 and val(0,3)=='Changed')
    page.locator('#confirm-action').click()
    check('Confirmed split writes to chosen destination', val(0,3)==1 and val(0,4)=='hello')
    hidden_roundtrip=page.evaluate("""async()=>{const w=new Gridline.Workbook();w.activeSheet.hiddenCols.add(2);w.activeSheet.colWidths.set(2,144);const restored=(await Gridline.importXLSX(await Gridline.exportXLSX(w))).workbook;return restored.activeSheet.hiddenCols.has(2)&&Math.abs(restored.activeSheet.colWidths.get(2)-144)<0.01;}""")
    check('XLSX round-trip preserves hidden columns and widths',hidden_roundtrip)
    check('Browser interactions produce no uncaught JavaScript errors', not errors, errors)
    goto('J1')
    page.evaluate("gridline.workbook.setCell(gridline.sheet,0,9,{raw:'45292',style:{format:'date',pattern:'yyyy-mm-dd'}})")
    page.evaluate("gridline.showTextToColumns()")
    page.locator('#split-delimiter').select_option('other')
    page.locator('#split-other').fill('-')
    check('Text to Columns previews displayed date separators', '2024' in page.locator('#split-preview').inner_text() and page.locator('#split-preview td').count() == 3)
    page.locator('[data-action="close-dialog"]').last.click()
    page.evaluate("gridline.showFormatCells()")
    page.locator('#format-category').select_option('time')
    check('Time format choices are visible as a list', page.locator('#format-pattern').evaluate('(el)=>el.clientHeight > 100 && el.options.length > 4'))
    page.locator('[data-action="close-dialog"]').last.click()
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;w.setCell(s,0,0,{raw:'19651',style:{format:'date',pattern:'mmm d, yyyy'}});w.setRaw(s,1,0,"'8/3/????");w.setCell(s,2,0,{raw:'19651',style:{format:'general'}});w.setCell(s,900000,0,{raw:'',style:{format:'date'}});w.setRaw(s,999999,8,'Other column');gridline.setWorkbook(w);}""")
    goto('A1:A1048576')
    copied = page.evaluate('gridline.clipboardPayload()')
    check('Whole-column copy trims empty tails and exports readable dates', copied.splitlines() == ['Oct 19, 1953','8/3/????','19651'] and page.evaluate('gridline.clipboard.cells.length') == 3, copied)
    page.evaluate('gridline.showTextToColumns()')
    page.locator('#split-delimiter').select_option('/')
    check('Slash splits a long formatted date into month day year', page.locator('#split-preview tr').first.locator('td').all_text_contents() == ['10','19','1953'])
    check('Unknown year text keeps its placeholder', page.locator('#split-preview tr').nth(1).locator('td').all_text_contents() == ['8','3','????'])
    page.locator('#split-delimiter').select_option('-')
    check('Hyphen also splits a formatted date', page.locator('#split-preview tr').first.locator('td').all_text_contents() == ['10','19','1953'])
    page.locator('#split-delimiter').select_option('date')
    check('Date parts interprets an unformatted Excel serial explicitly', page.locator('#split-preview tr').nth(2).locator('td').all_text_contents() == ['10','19','1953'])
    page.locator('#split-destination').fill('C1')
    page.locator('#split-apply').click()
    check('Finish writes three new columns and preserves source dates', [val(0,c) for c in range(2,5)] == [10,19,1953] and [val(1,c) for c in range(2,5)] == [8,3,'????'] and val(0,0) == 19651)
    page.evaluate('gridline.workbook.undo()')
    check('Date splitting undoes in one step', val(0,2) is None and val(0,0) == 19651)
    goto('A1')
    page.evaluate('gridline.showFormatCells()')
    page.locator('#format-pattern').select_option('m/d')
    page.locator('#format-apply').click()
    check('Month/day format hides year while retaining numeric date', page.evaluate('gridline.workbook.display(gridline.sheet,0,0)') == '10/19' and val(0,0) == 19651)
    check('Date and bounded-copy regressions have no uncaught errors', not errors, errors)
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;w.setCell(s,6,14,{raw:'31794',style:{format:'date',pattern:'mmm d, yyyy'}});w.setCell(s,12,14,{raw:'19877',style:{format:'date',pattern:'mmm d, yyyy'}});w.setRaw(s,0,15,'1987');w.setRaw(s,13,14,'=1900+87');gridline.setWorkbook(w);}""")
    goto('O1:O1048576')
    page.evaluate('gridline.showFind()')
    page.locator('#find-scope').select_option('column')
    page.locator('#find-query').fill('1987')
    check('Find defaults to displayed values and excludes hidden date serials', page.locator('#find-look-in').input_value() == 'display' and page.locator('#find-results b').all_text_contents() == ['O7','O14'])
    page.locator('#replace-query').fill('2000')
    page.locator('#replace-all').click()
    check('Displayed search replacement cannot modify a hidden serial match', val(12,14) == 19877)
    page.evaluate('gridline.workbook.undo()')
    page.locator('#find-look-in').select_option('raw')
    check('Original-value search explicitly finds and shows the stored serial', page.locator('#find-results b').all_text_contents() == ['O13'] and page.locator('#find-results span').inner_text() == '19877')
    page.locator('#find-query').fill('1900+87')
    check('Original-value mode searches formula text', page.locator('#find-results b').all_text_contents() == ['O14'])
    page.locator('#find-look-in').select_option('display')
    check('Displayed-value mode excludes hidden formula text', page.locator('#find-results b').count() == 0)
    page.locator('[data-action="close-panel"]').click()
    check('Find regressions have no uncaught browser errors', not errors, errors)
    wheel_results = page.evaluate("""()=>{const r=gridline.renderer,host=document.querySelector('#grid-host');r.scrollX=500;r.scrollY=500;const steps=[{deltaY:120},{deltaY:120,shiftKey:true},{deltaX:120,shiftKey:true},{deltaX:-120,shiftKey:true},{deltaY:-120,shiftKey:true},{deltaX:80},{deltaY:2,deltaMode:1,shiftKey:true}];return steps.map(step=>{host.dispatchEvent(new WheelEvent('wheel',{...step,bubbles:true,cancelable:true}));return [r.scrollX,r.scrollY];});}""")
    check('Wheel scrolls vertically and Shift+wheel accepts either browser axis in both directions', wheel_results == [[500,620],[620,620],[740,620],[620,620],[500,620],[580,620],[630,620]], wheel_results)
    page.locator('[data-tab="Home"]').click()
    goto('B2:C3')
    page.locator('#ribbon [data-action="fill-color"]').click()
    check('Fill Color opens a visible color dialog', page.locator('#color-picker').is_visible())
    page.locator('[data-swatch="#ffc000"]').click()
    page.locator('#color-apply').click()
    check('Fill Color applies a swatch to the full selection', page.evaluate('[1,2].every(r=>[1,2].every(c=>gridline.sheet.style(r,c).fill==="#ffc000"))'))
    page.locator('[data-action="text-color"]').click()
    check('Text Color opens a visible color dialog', page.locator('#color-picker').is_visible())
    page.locator('#color-hex').fill('#123ABC')
    page.locator('#color-apply').click()
    check('Text Color applies a custom color without changing fill', page.evaluate('[1,2].every(r=>[1,2].every(c=>gridline.sheet.style(r,c).color==="#123abc" && gridline.sheet.style(r,c).fill==="#ffc000"))'))
    page.evaluate('gridline.workbook.undo()')
    check('Color formatting undoes as one operation', page.evaluate('[1,2].every(r=>[1,2].every(c=>!gridline.sheet.style(r,c).color && gridline.sheet.style(r,c).fill==="#ffc000"))'))
    page.locator('#ribbon [data-action="fill-color"]').click()
    page.locator('[data-swatch="#ff0000"]').click()
    page.locator('[data-action="close-dialog"]').last.click()
    check('Cancel leaves cell colors unchanged', page.evaluate('gridline.sheet.style(1,1).fill === "#ffc000"'))
    cell=page.evaluate('gridline.renderer.cellRect(1,1,false)')
    host=page.locator('#grid-host').bounding_box()
    page.mouse.click(host['x']+cell['x']+cell['w']/2,host['y']+cell['y']+cell['h']/2,button='right')
    page.locator('#context-menu [data-action="fill-color"]').click()
    page.locator('[data-swatch="#7030a0"]').click()
    page.locator('#color-apply').click()
    check('Right-click Fill Color preserves and colors the selected range',page.evaluate('[1,2].every(r=>[1,2].every(c=>gridline.sheet.style(r,c).fill==="#7030a0"))'))
    page.evaluate('gridline.workbook.undo()')
    page.locator('.sheet-tab.selected').click(button='right')
    page.locator('#context-menu [data-action="tab-color"]').click()
    page.locator('#color-hex').fill('#123ABC')
    page.locator('#color-apply').click()
    check('Tab Color applies a custom color and persists in workbook snapshots',page.evaluate('gridline.sheet.color==="#123abc" && Gridline.Workbook.fromJSON(gridline.workbook.toJSON()).activeSheet.color==="#123abc"') and page.locator('.sheet-tab.selected .sheet-tab-dot').evaluate('(e)=>getComputedStyle(e).backgroundColor')=='rgb(18, 58, 188)')
    page.locator('.sheet-tab.selected').click(button='right')
    page.locator('#context-menu [data-action="tab-color"]').click()
    page.locator('#color-clear').click()
    check('No Color clears the sheet tab marker',page.evaluate('gridline.sheet.color===null') and page.locator('.sheet-tab.selected .sheet-tab-dot').evaluate('(e)=>getComputedStyle(e).backgroundColor')=='rgba(0, 0, 0, 0)')
    page.evaluate('gridline.workbook.undo()')
    check('Tab color changes support undo',page.evaluate('gridline.sheet.color==="#123abc"'))
    check('Color interactions have no uncaught browser errors', not errors, errors)
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;w.setCell(s,0,0,{raw:'19651',style:{format:'date',pattern:'m/d/yyyy'}});w.setRaw(s,1,0,"'8/3/????");w.setRaw(s,99,0,'last row');w.setCell(s,900000,0,{raw:'',style:{fill:'#ffffff'}});gridline.setWorkbook(w);}""")
    goto('A1:A2')
    page.evaluate('gridline.showFind()')
    page.locator('#find-query').fill('/')
    page.locator('#replace-query').fill(',')
    page.locator('#replace-all').click()
    check('Replace changes visible date separators and unknown-year text', val(0,0) == '10,19,1953' and val(1,0) == '8,3,????')
    page.evaluate('gridline.workbook.undo()')
    check('Undo restores numeric dates after displayed replacement', val(0,0) == 19651 and val(1,0) == '8/3/????')
    page.locator('[data-action="close-panel"]').click()
    page.evaluate('gridline.updateScrollbars()')
    track = page.locator('#v-scrollbar').bounding_box()
    page.mouse.click(track['x']+track['width']/2,track['y']+track['height']-2)
    check('Clicking scrollbar bottom stops at last populated row, ignoring formatting-only cells', page.evaluate('gridline.renderer.populatedRows===100 && Math.abs(gridline.renderer.scrollY-Math.max(0,gridline.renderer.rows.offset(100)*gridline.renderer.zoom-gridline.renderer.height+gridline.renderer.headerH))<1'))
    goto('A150')
    page.keyboard.type('new last row')
    page.keyboard.press('Enter')
    check('Entering data beyond scrollbar extent expands it', page.evaluate('gridline.renderer.populatedRows===150'))
    page.evaluate('gridline.setWorkbook(new Gridline.Workbook());gridline.updateScrollbars()')
    track = page.locator('#v-scrollbar').bounding_box()
    page.mouse.click(track['x']+track['width']/2,track['y']+track['height']-2)
    check('Empty-sheet scrollbar does not jump or produce negative scroll', page.evaluate('gridline.renderer.scrollY===0'))
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;w.setRaw(s,0,2,'Wide household heading');w.setRaw(s,0,3,'ID');w.setRaw(s,0,4,'Prefix');w.setRaw(s,0,5,'Given name');w.setRaw(s,1,6,'=SUM(C2:F2)');s.merges=[{r1:2,r2:2,c1:2,c2:3}];gridline.setWorkbook(w);}""")
    goto('C1:F1048576')
    point = page.evaluate('gridline.renderer.cellRect(1,3,false)')
    host = page.locator('#grid-host').bounding_box()
    page.evaluate("""p=>{const host=document.querySelector('#grid-host');host.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,button:0,ctrlKey:true,clientX:p.x,clientY:p.y}));host.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,ctrlKey:true,clientX:p.x,clientY:p.y}));}""", {'x':host['x']+point['x']+10,'y':host['y']+point['y']+10})
    check('Ctrl-click context menu preserves selected columns', page.evaluate('gridline.selection.c1===2 && gridline.selection.c2===5 && gridline.selection.r2===1048575'))
    page.locator('#context-menu [data-action="insert-column"]').click()
    check('Insert creates four columns and shifts formulas and merges', val(0,6)=='Wide household heading' and page.evaluate('gridline.sheet.raw(1,10)==="=SUM(G2:J2)" && gridline.sheet.merges[0].c1===6 && gridline.sheet.merges[0].c2===7'))
    page.evaluate('gridline.workbook.undo()')
    check('Multiple column insertion undoes as one operation', val(0,2)=='Wide household heading' and page.evaluate('gridline.sheet.raw(1,6)==="=SUM(C2:F2)"'))
    goto('C1:F1048576')
    point = page.evaluate('gridline.renderer.cellRect(0,4,false)')
    page.mouse.dblclick(host['x']+point['x']+point['w'],host['y']+12)
    check('Double-clicking selected column separator auto-fits all selected columns', page.evaluate('[2,3,4,5].every(c=>gridline.sheet.colWidths.has(c)) && gridline.sheet.colWidths.get(2)>gridline.sheet.colWidths.get(3) && !gridline.sheet.colWidths.has(6)'))
    check('Auto-fit preserves the whole-column selection', page.evaluate('gridline.selection.c1===2 && gridline.selection.c2===5 && gridline.selection.r2===1048575'))
    font_fixture = io.BytesIO()
    with zipfile.ZipFile(font_fixture, 'w') as z:
        z.writestr('xl/workbook.xml', '<workbook xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Fonts" r:id="r1"/></sheets></workbook>')
        z.writestr('xl/_rels/workbook.xml.rels', '<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/><Relationship Id="r2" Target="styles.xml"/></Relationships>')
        z.writestr('xl/styles.xml', '<styleSheet><fonts><font><b val="0"/><i val="false"/><u val="none"/></font><font><b val="1"/><i val="0"/><u val="none"/></font></fonts><cellXfs><xf fontId="0"/><xf fontId="1"/></cellXfs></styleSheet>')
        z.writestr('xl/worksheets/sheet1.xml', '<worksheet><sheetData><row r="1"><c r="A1" s="1"><v>1</v></c></row><row r="2"><c r="A2" s="0"><v>2</v></c></row></sheetData></worksheet>')
    font_flags = page.evaluate("""async b=>{const w=(await Gridline.importXLSX(Uint8Array.from(atob(b),c=>c.charCodeAt(0)))).workbook;return [w.activeSheet.style(0,0),w.activeSheet.style(1,0)];}""", base64.b64encode(font_fixture.getvalue()).decode())
    check('XLSX honors explicit false font flags and underline none', font_flags[0]['bold'] and not font_flags[0]['italic'] and not font_flags[0]['underline'] and not font_flags[1]['bold'] and not font_flags[1]['italic'] and not font_flags[1]['underline'], font_flags)
    page.evaluate("testFileLaunch({files:[]})")
    page.evaluate("testFileLaunch({files:[{getFile:async()=>new File(['Name,Year\\nExample,1987'],'launch.csv',{type:'text/csv'})}]})")
    page.wait_for_function('gridline.workbook.title === "launch"')
    check('Chrome file launch opens CSV with the existing importer', val(1,0)=='Example' and val(1,1)==1987)
    page.evaluate("""async()=>{const w=new Gridline.Workbook();w.setRaw(w.activeSheet,0,0,'From Excel');const bytes=await Gridline.exportXLSX(w);testFileLaunch({files:[{getFile:async()=>new File([bytes],'launch-excel.xlsx')}]});}""")
    page.wait_for_function('gridline.workbook.title === "launch-excel"')
    check('Chrome file launch opens XLSX with the existing importer',val(0,0)=='From Excel')
    page.evaluate("testFileLaunch({files:[{getFile:async()=>{throw new Error('File permission test');}}]})")
    page.wait_for_function('document.querySelector("#toast").textContent === "File permission test"')
    check('Failed file launch preserves the active workbook', val(0,0)=='From Excel')
    if args.url:
        manifest = page.evaluate("async()=>{const response=await fetch(document.querySelector('link[rel=manifest]').href);return {type:response.headers.get('content-type'),data:await response.json()};}")
        check('Served build exposes install manifest and file handlers', 'application/manifest+json' in manifest['type'] and manifest['data']['file_handlers'][0]['launch_type']=='multiple-clients')
        check('App icons load from the deployment subdirectory', page.evaluate("async()=>{const m=new URL(document.querySelector('link[rel=manifest]').href);const data=await(await fetch(m)).json();return (await Promise.all(data.icons.map(async icon=>{const response=await fetch(new URL(icon.src,m));return response.ok && response.headers.get('content-type').startsWith('image/png');}))).every(Boolean);}"))
        cdp = page.context.new_cdp_session(page)
        check('Chrome reports no manifest installability errors', not [e for e in cdp.send('Page.getInstallabilityErrors')['installabilityErrors'] if e['errorId'] != 'in-incognito'])
    check('File launch tests have no uncaught browser errors',not errors,errors)
    saved_startup = page.evaluate("JSON.stringify(Gridline.createSampleWorkbook().toJSON())")
    for reopen in [False,True]:
        startup_page = browser.new_page()
        seed = {'gridline.workbook.v1':saved_startup,'gridline.reopen-last.v1':str(reopen).lower()}
        startup_storage = '<script>Object.defineProperty(window,"localStorage",{value:(()=>{const m=new Map(Object.entries('+json.dumps(seed)+'));return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v))};})()});</script>'
        startup_page.set_content((ROOT/'dist/index.html').read_text().replace('<head>','<head>'+startup_storage,1),wait_until='networkidle')
        startup_page.wait_for_function('window.gridline?.ready')
        check('Startup restores only when reopen is enabled: '+str(reopen), startup_page.evaluate('gridline.workbook.sheets.length') == (3 if reopen else 1) and startup_page.locator('#dialog').evaluate('(el)=>el.open') == (not reopen))
        startup_page.evaluate('gridline.persist()')
        check('Idle disabled startup preserves previous autosave: '+str(reopen), startup_page.evaluate('localStorage.getItem("gridline.workbook.v1")') == saved_startup)
        if not reopen:
            startup_page.locator('#reopen-now').click()
            check('Reopen now restores the saved workbook without enabling auto-reopen',startup_page.evaluate('gridline.workbook.sheets.length===3 && !gridline.dialog.open && !gridline.reopenLast') and startup_page.evaluate('localStorage.getItem("gridline.reopen-last.v1")')=='false')
        startup_page.close()
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;['Alpha','alpha','Alphabet','A.b','axb'].forEach((v,r)=>w.setRaw(s,r,0,v));gridline.setWorkbook(w);}""")
    goto('A1:A5')
    page.evaluate('gridline.showFind()')
    page.locator('#find-query').fill('Alpha')
    check('Find defaults to case-insensitive partial matching', page.locator('#find-results b').count()==3)
    page.locator('#find-match-case').check()
    check('Match Case filters results immediately', page.locator('#find-results b').count()==2)
    page.locator('#find-entire').check()
    check('Entire cells and Match Case combine', page.locator('#find-results b').all_text_contents()==['A1'])
    page.locator('#replace-query').fill('Changed')
    page.locator('#replace-all').click()
    check('Replace uses both matching options', val(0,0)=='Changed' and val(1,0)=='alpha' and val(2,0)=='Alphabet')
    page.evaluate('gridline.workbook.undo()')
    page.locator('#find-match-case').uncheck()
    check('Entire-cell matching can ignore case', page.locator('#find-results b').count()==2)
    page.locator('#replace-all').click()
    check('Case-insensitive replacement updates both complete matches', val(0,0)=='Changed' and val(1,0)=='Changed' and val(2,0)=='Alphabet')
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,1,0,'Alpha\\n')")
    page.locator('#find-query').fill('Alpha')
    check('Entire-cell matching includes trailing line breaks', page.locator('#find-results b').count()==0)
    page.locator('#find-entire').uncheck()
    page.locator('#find-query').fill('a.b')
    page.locator('#replace-query').fill('$&')
    page.locator('#replace-all').click()
    check('Find and replacement treat punctuation literally', val(3,0)=='$&' and val(4,0)=='axb')
    page.locator('[data-action="close-panel"]').click()
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,0,4,'Keep')")
    goto('B1:D1048576')
    page.evaluate("gridline.run('delete-column')")
    check('Delete removes every highlighted column', val(0,1)=='Keep')
    page.evaluate('gridline.workbook.undo()')
    check('Multi-column delete undoes as one edit', val(0,4)=='Keep' and val(0,1) is None)
    page.evaluate("""()=>{window.originalSavePicker=window.showSaveFilePicker;window.saveChunks=[];window.savedClosed=false;window.showSaveFilePicker=async options=>{window.saveOptions=options;return {createWritable:async()=>new WritableStream({write:chunk=>saveChunks.push(...chunk),close:()=>window.savedClosed=true})};};}""")
    page.evaluate("gridline.showExport()")
    page.locator('#dialog [data-action="export-xlsx"]').click()
    page.wait_for_function('savedClosed')
    check('Excel export prompts for a destination and writes a valid workbook', page.evaluate("async()=>saveOptions.suggestedName.endsWith('.xlsx') && (await Gridline.importXLSX(new Uint8Array(saveChunks))).workbook.sheets.length===gridline.workbook.sheets.length"))
    page.evaluate("window.showSaveFilePicker=async()=>{throw new DOMException('Cancelled','AbortError')};gridline.showExport()")
    page.locator('#dialog [data-action="export-xlsx"]').click()
    check('Cancelling Save As leaves export dialog open', page.locator('#dialog').evaluate('(el)=>el.open'))
    page.evaluate("window.showSaveFilePicker=async()=>({createWritable:async()=>new WritableStream({write:()=>{throw new Error('Save failed test')}})});")
    page.locator('#dialog [data-action="export-xlsx"]').click()
    page.wait_for_function('document.querySelector("#toast").textContent==="Save failed test"')
    check('Failed Excel save reports the error without claiming success', page.locator('#dialog').evaluate('(el)=>el.open'))
    page.evaluate('window.showSaveFilePicker=undefined')
    with page.expect_download() as exported:
        page.locator('#dialog [data-action="export-xlsx"]').click()
    check('Browsers without Save As retain Excel downloads', exported.value.suggested_filename.endswith('.xlsx'))
    page.evaluate('window.showSaveFilePicker=window.originalSavePicker')
    page.evaluate('gridline.setWorkbook(new Gridline.Workbook())')
    for arrow, row, col in [('ArrowRight',2,3),('ArrowLeft',2,1),('ArrowDown',3,2),('ArrowUp',1,2)]:
        goto('C3')
        page.keyboard.type('123')
        page.keyboard.press(arrow)
        check(arrow+' saves the typed value and moves one cell', val(2,2)==123 and page.evaluate('gridline.active')=={'r':row,'c':col} and not page.evaluate('gridline.editing'))
    goto('C3')
    page.keyboard.type('=1+2')
    page.keyboard.press('ArrowRight')
    check('Arrow commit calculates formulas and supports undo', val(2,2)==3)
    page.evaluate('gridline.workbook.undo()')
    check('Undo restores the value before arrow commit',val(2,2)==123)
    goto('A1')
    page.keyboard.type('edge')
    page.keyboard.press('ArrowLeft')
    check('Arrow commit stays within sheet boundaries',val(0,0)=='edge' and page.evaluate('gridline.active.c')==0)
    page.evaluate("gridline.workbook.applyStyle(gridline.sheet,{r1:0,r2:0,c1:1,c2:1},{format:'date'})")
    goto('B1')
    page.keyboard.type('2026-02-30')
    page.keyboard.press('ArrowDown')
    check('Invalid dates remain editable instead of moving or saving',page.evaluate('gridline.editing && gridline.active.r===0 && gridline.active.c===1') and val(0,1) is None)
    page.keyboard.press('Escape')
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;w.setRaw(s,0,0,'2');w.setRaw(s,1,0,'3');w.setRaw(s,2,0,'4');w.setRaw(s,4,0,'9');w.setCell(s,0,1,{raw:'=A1*$A$1',style:{fill:'#ffff00'}});gridline.setWorkbook(w);}""")
    def double_fill(ref):
        goto(ref)
        handle=page.evaluate('gridline.renderer.cellRect(gridline.active.r,gridline.active.c,false)')
        host=page.locator('#grid-host').bounding_box()
        page.mouse.dblclick(host['x']+handle['x']+handle['w']-1,host['y']+handle['y']+handle['h']-1)
    double_fill('B1')
    check('Double-click fill handle copies formulas through adjacent data', val(1,1)==6 and val(2,1)==8 and page.evaluate('gridline.sheet.raw(2,1)==="=A3*$A$1" && gridline.sheet.style(2,1).fill==="#ffff00"'))
    check('Automatic fill stops at the first empty adjoining row',val(3,1) is None and val(4,1) is None and not page.evaluate('gridline.editing'))
    page.evaluate('gridline.workbook.undo()')
    check('Automatic fill undoes in one step',val(1,1) is None and val(2,1) is None and val(0,1)==4)
    goto('B1')
    handle=page.evaluate('gridline.renderer.cellRect(0,1,false)')
    host=page.locator('#grid-host').bounding_box()
    x,y=host['x']+handle['x']+handle['w']-1,host['y']+handle['y']+handle['h']-1
    page.mouse.move(x,y)
    page.mouse.down()
    page.mouse.move(x+2,y+2)
    page.mouse.up()
    check('Fill handle ignores click jitter across the cell boundary',page.evaluate('gridline.selection.r2===0 && gridline.selection.c2===1') and val(1,1) is None and val(1,2) is None)
    page.mouse.down(click_count=2)
    page.mouse.up(click_count=2)
    check('Double-click with pointer jitter still autofills without editing',val(2,1)==8 and not page.evaluate('gridline.editing'))
    page.evaluate('gridline.workbook.undo()')
    check('Jittered double-click remains a single undo step',val(1,1) is None and val(2,1) is None)
    goto('B1')
    page.mouse.move(x,y)
    page.mouse.down()
    page.mouse.move(x,y+handle['h']*2)
    page.mouse.move(x,y+2)
    page.mouse.up()
    check('A deliberate fill drag stays active when returning near its start',val(1,1)==6 and val(2,1) is None)
    page.evaluate('gridline.workbook.undo()')
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,0,4,'Repeat')")
    double_fill('E1')
    check('Fill handle does nothing without adjacent data below',val(1,4) is None and not page.evaluate('gridline.editing'))
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,1,5,'0');gridline.workbook.setRaw(gridline.sheet,2,5,'row')")
    double_fill('E1')
    check('Automatic fill also uses right-hand data and copies literal text',val(1,4)=='Repeat' and val(2,4)=='Repeat' and val(3,4) is None)
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;w.setRaw(s,0,0,'5');w.setCell(s,0,1,{raw:'=A1*2',style:{fill:'#ffff00'}});w.setRaw(s,1,0,'Text');gridline.setWorkbook(w);}""")
    page.locator('[data-tab="Home"]').click()
    goto('A1:B2')
    page.locator('#ribbon [data-action="copy"]').click()
    check('Block copy preserves trailing empty cells and marks its range',page.evaluate('gridline.clipboard.cells.length===2 && gridline.clipboard.cells[1].length===2 && gridline.renderer.copyRange.c2===1'))
    goto('D1')
    page.locator('[data-action="paste-menu"]').click()
    check('Paste dropdown offers all three modes',page.locator('#context-menu [data-action]').all_text_contents()==['Paste','Paste as Values','Paste as Formula'])
    page.locator('#context-menu [data-action="paste-values"]').click()
    check('Paste as Values uses numeric formula results without source formatting',val(0,4)==10 and page.evaluate('gridline.sheet.raw(0,4)==="10" && !gridline.sheet.style(0,4).fill') and val(1,3)=='Text')
    goto('G1')
    page.locator('[data-action="paste-menu"]').click()
    page.locator('#context-menu [data-action="paste-formula"]').click()
    check('Paste as Formula shifts references without source formatting',page.evaluate('gridline.sheet.raw(0,7)==="=G1*2" && !gridline.sheet.style(0,7).fill') and val(0,7)==10)
    goto('J1:K4')
    page.locator('#ribbon [data-action="paste"]').click()
    check('Paste repeats a block to fill a compatible selection',val(0,10)==10 and val(2,10)==10 and val(3,9)=='Text' and page.evaluate('gridline.sheet.style(0,10).fill==="#ffff00"'))
    goto('D1')
    page.locator('#ribbon [data-action="paste"]').click()
    check('Paste asks before overwriting existing data',page.locator('#confirm-action').count()==1)
    page.locator('[data-action="close-dialog"]').last.click()
    check('Cancel preserves destination contents and formatting',page.evaluate('!gridline.sheet.style(0,4).fill'))
    page.locator('#ribbon [data-action="paste"]').click()
    page.locator('#confirm-action').click()
    check('Confirmed paste copies formulas and formatting',page.evaluate('gridline.sheet.raw(0,4)==="=D1*2" && gridline.sheet.style(0,4).fill==="#ffff00"'))
    page.evaluate('gridline.workbook.undo()')
    check('Paste overwrite undoes as a single action',page.evaluate('gridline.sheet.raw(0,4)==="10" && !gridline.sheet.style(0,4).fill'))
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;['Gender','Female','Male','Female','','Male','Female'].forEach((v,r)=>w.setRaw(s,r,0,v));w.setCell(s,900000,0,{raw:'',style:{fill:'#ffff00'}});gridline.setWorkbook(w);}""")
    goto('A1:A1048576')
    page.locator('[data-tab="Data"]').click()
    page.locator('[data-action="analyze-data"]').click()
    check('Analyze Data counts selected-column values and blanks without empty tails', page.locator('#analyze-results tbody tr').all_text_contents()==['Female3','Male2','(blank)1'] and '6 rows' in page.locator('#analyze-summary').inner_text())
    page.locator('#analyze-header').uncheck()
    check('Analyze Data can include the first row', 'Gender1' in page.locator('#analyze-results tbody tr').all_text_contents())
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,3,0,'Male')")
    page.locator('#analyze-refresh').click()
    check('Analyze Data refreshes counts after edits', page.locator('#analyze-results tbody tr').first.inner_text()=='Male\t3')
    page.locator('[data-action="close-panel"]').click()
    page.evaluate("gridline.workbook.setCell(gridline.sheet,0,1,{raw:'19651',style:{format:'date',pattern:'m/d/yyyy'}});gridline.workbook.setCell(gridline.sheet,1,1,{raw:'19651',style:{format:'date',pattern:'m/d/yyyy'}})")
    goto('B1:B2')
    page.locator('[data-action="analyze-data"]').click()
    page.locator('#analyze-header').uncheck()
    check('Analyze Data groups displayed dates rather than serial numbers', page.locator('#analyze-results tbody tr').all_text_contents()==['10/19/19532'])
    page.locator('[data-action="close-panel"]').click()
    goto('A3:A4')
    page.locator('[data-action="analyze-data"]').click()
    check('Analyze Data respects a selected row range',page.locator('#analyze-results tbody tr').all_text_contents()==['Male2'])
    page.locator('[data-action="close-panel"]').click()
    goto('H1')
    page.locator('[data-action="analyze-data"]').click()
    check('Analyze Data handles an empty column',page.locator('#analyze-results').inner_text()=='No data to analyze.')
    page.locator('[data-action="close-panel"]').click()
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;['Alpha','beta','ALPHABET','','=""',' ','=1/0','="Alpha"'].forEach((v,r)=>w.setRaw(s,r,0,v));w.setRaw(s,0,1,'Alpha');gridline.setWorkbook(w);}""")
    goto('A1:A8')
    page.locator('[data-tab="Home"]').click()
    def highlighted_rows():
        return page.evaluate("""()=>{const r=gridline.renderer;r.draw();return Array.from({length:8},(_,i)=>{const p=r.cellRect(i,0,false);return r.commands.some(c=>c.kind==='rect'&&c.color==='#d9eee3'&&c.x===p.x&&c.y===p.y&&c.w===p.w&&c.h===p.h);});}""")
    page.locator('#ribbon [data-action="conditional"]').click()
    page.locator('[data-rule="contains"]').click()
    page.locator('#cf-apply').click()
    check('Specific text rules require text before applying',page.locator('#dialog').evaluate('(e)=>e.open') and page.evaluate('gridline.sheet.conditionalRules.length===0'))
    page.locator('#cf-text').fill('alpha')
    page.locator('[data-rule="contains"]').click()
    page.locator('#cf-apply').click()
    check('Containing text matches case-insensitively including formula results',highlighted_rows()==[True,False,True,False,False,False,False,True])
    check('Conditional text rules survive workbook serialization',page.evaluate('Gridline.Workbook.fromJSON(gridline.workbook.toJSON()).activeSheet.conditionalRules[0].value==="alpha"'))
    page.evaluate("gridline.workbook.setRaw(gridline.sheet,1,0,'Alpha now')")
    check('Text highlighting updates when cell contents change',highlighted_rows()[1])
    page.evaluate('gridline.workbook.undo();gridline.workbook.undo()')
    check('Conditional rule creation supports undo',not any(highlighted_rows()))
    page.locator('#ribbon [data-action="conditional"]').click()
    page.locator('[data-rule="not-contains"]').click()
    page.locator('#cf-text').fill('alpha')
    page.locator('#cf-apply').click()
    check('Not containing excludes blank cells and formula errors',highlighted_rows()==[False,True,False,False,False,True,False,False])
    page.evaluate('gridline.workbook.undo()')
    page.locator('#ribbon [data-action="conditional"]').click()
    page.locator('[data-rule="blank"]').click()
    page.locator('#cf-apply').click()
    check('Blank highlights empty cells and empty formula results, not spaces',highlighted_rows()==[False,False,False,True,True,False,False,False])
    page.locator('#ribbon [data-action="conditional"]').click()
    page.locator('#clear-rules').click()
    check('Clear rules removes conditional highlights',not any(highlighted_rows()))
    page.evaluate("""()=>{const w=new Gridline.Workbook(),s=w.activeSheet;['Jim and Jane Smith','Jim/Jane Smith','Jim & Jane Smith','Jim and Jane Smith-Watson','Jim Smith & Ruby Weeks','Jim, Jane, Billy, Sally, Allison Smith','Unknown'].forEach((v,r)=>w.setRaw(s,r,0,v));w.setRaw(s,0,1,'SMITH, Jim and Jane');w.setRaw(s,2,1,'Keep me');gridline.setWorkbook(w);}""")
    goto('A1:A7')
    page.locator('[data-tab="Data"]').click()
    page.locator('[data-action="fill-example"]').click()
    check('Fill from Example uses the adjacent example and previews household results',page.locator('#fill-example').input_value()=='SMITH, Jim and Jane' and '4 cells to fill' in page.locator('#fill-preview').inner_text() and 'SMITH-WATSON, Jim and Jane' in page.locator('#fill-preview').inner_text())
    page.locator('#fill-example').fill('Different pattern')
    check('Unsupported examples cannot apply',page.locator('#fill-apply').is_disabled())
    page.locator('#fill-example').fill('SMITH, Jim and Jane')
    page.locator('#fill-destination').fill('A1')
    check('Fill from Example prevents writing into the source',page.locator('#fill-apply').is_disabled())
    page.locator('#fill-destination').fill('B1')
    page.locator('#fill-apply').click()
    check('Household fill preserves entries, skips unrecognized names, and truncates lists',page.evaluate('Array.from({length:7},(_,r)=>gridline.sheet.raw(r,1))')==['SMITH, Jim and Jane','SMITH, Jim and Jane','Keep me','SMITH-WATSON, Jim and Jane','SMITH, Jim and Ruby Weeks','SMITH, Jim and Jane',''])
    page.evaluate('gridline.workbook.undo()')
    check('Household fill undoes in one step',page.evaluate('gridline.sheet.raw(1,1)==="" && gridline.sheet.raw(5,1)==="" && gridline.sheet.raw(2,1)==="Keep me"'))
    page.evaluate('gridline.workbook.redo()')
    check('Household fill supports redo',page.evaluate('gridline.sheet.raw(5,1)==="SMITH, Jim and Jane"'))
    page.evaluate("localStorage.removeItem('gridline.workbook.v1');gridline.showFile()")
    page.locator('#reopen-now').click()
    check('Reopen now explains when no saved copy exists', 'No saved workbook' in page.locator('#toast').inner_text() and page.locator('#dialog').evaluate('(el)=>el.open'))
    page.evaluate("localStorage.setItem('gridline.workbook.v1','invalid json')")
    before_reopen = page.evaluate('gridline.workbook.title')
    page.locator('#reopen-now').click()
    check('Invalid saved workbook leaves the current workbook intact',page.evaluate('gridline.workbook.title')==before_reopen and page.locator('#dialog').evaluate('(el)=>el.open'))
    page.evaluate('gridline.persist()')
    page.locator('#reopen-now').click()
    check('Reopen now asks before replacing an active workbook',page.locator('#confirm-action').count()==1)
    page.locator('[data-action="close-dialog"]').last.click()
    report={'harness':'served origin' if args.url else 'inline opaque origin, in-memory Storage fixture','browser':browser.version,'backend':backend,'passed':len(checks),'checks':checks,'stressMetrics':metrics,'uncaughtErrors':errors,'notes':['GPU execution is verified only when backend is webgpu.','CPU frame measurement is not GPU completion time or a cross-machine benchmark.','In-memory storage fixture does not validate real browser persistence.']}
    (ROOT/'docs/browser-test-results.json').write_text(json.dumps(report,indent=2))
    print(json.dumps({'passed':len(checks),'backend':backend,'stress':metrics},indent=2))
    browser.close()
