"""Browser integration tests. Install Python Playwright separately; no app dependencies.
Defaults to an inline, opaque-origin harness; --url exercises a locally served build.
The inline harness uses an in-memory Storage fixture, not persistent browser storage.
"""
from pathlib import Path
import argparse, base64, io, json, os, time, zipfile
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--url', default=None)
parser.add_argument('--chromium', default=os.getenv('CHROMIUM', '/usr/bin/chromium'))
args = parser.parse_args()
checks = []
def check(name, condition, detail=None):
    if not condition:
        raise AssertionError(f'{name}: {detail}')
    checks.append({'name': name, 'passed': True, 'detail': detail})
    print('PASS', name, flush=True)

with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=args.chromium, headless=True, args=['--no-sandbox'])
    page = browser.new_page(viewport={'width':1536, 'height':1240}, device_scale_factor=1)
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    if args.url:
        page.goto(args.url, wait_until='networkidle')
    else:
        storage = '''<script>(()=>{const m=new Map();Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),clear:()=>m.clear(),key:i=>[...m.keys()][i]??null,get length(){return m.size}}});})();</script>'''
        html = (ROOT/'dist/index.html').read_text()
        page.set_content(html.replace('<head>', '<head>'+storage, 1), wait_until='networkidle')
    page.wait_for_function('window.gridline && window.gridline.ready', timeout=45000)
    page.wait_for_timeout(300)
    backend = page.evaluate('({backend:gridline.renderer.backend,reason:gridline.renderer.fallbackReason})')
    check('Standalone app boots without an uncaught exception', not errors, errors)
    check('Demo total is calculated', page.evaluate('gridline.workbook.value(gridline.sheet,5,1)') == 2187000)
    check('Demo has three sheets and two chart overlays', page.locator('.sheet-tab').count()==3 and page.locator('.chart-card').count()==2)
    (ROOT/'docs').mkdir(exist_ok=True)
    page.screenshot(path=str(ROOT/'docs/preview.png'), full_page=True)
    def goto(ref):
        page.locator('#name-box').fill(ref)
        page.locator('#name-box').press('Enter')
    def val(r,c):
        return page.evaluate('p=>gridline.workbook.value(gridline.sheet,p[0],p[1])',[r,c])
    goto('D12')
    page.keyboard.type('200000')
    page.keyboard.press('Enter')
    check('Typing commits a real numeric cell', val(11,3)==200000, val(11,3))
    check('Editing recalculates dependent total', val(5,1)==2219000, val(5,1))
    page.keyboard.press('Control+z')
    check('Keyboard undo restores both input and calculated total', val(11,3)==168000 and val(5,1)==2187000)
    page.keyboard.press('Control+y')
    check('Keyboard redo reapplies the transaction', val(11,3)==200000)
    page.keyboard.press('Control+z')
    goto('G13')
    page.locator('#formula-input').fill('=SUM(D13:F13)+1000')
    page.locator('#formula-input').press('Enter')
    check('Formula bar parses, commits, and calculates', val(12,6)==409000, val(12,6))
    page.keyboard.press('Control+z')
    page.locator('[data-action="add-sheet"]').click()
    check('New worksheet command creates a sheet', page.evaluate('gridline.workbook.sheets.length')==4)
    goto('A1')
    # Native paste event path, including multiline data and formulas.
    page.evaluate('''()=>{const d=new DataTransfer();d.setData('text/plain','Item\\tUnits\\tPrice\\tRevenue\\nAlpha\\t2\\t10\\t=B2*C2\\nBeta\\t3\\t20\\t=B3*C3');document.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));}''')
    check('Clipboard paste event enters a rectangular range', val(1,0)=='Alpha' and val(2,1)==3)
    check('Pasted formulas calculate', val(1,3)==20 and val(2,3)==60)
    goto('D2:D6')
    page.keyboard.press('Control+d')
    check('Fill-down shifts relative references', page.evaluate('gridline.sheet.raw(5,3)')=='=B6*C6')
    goto('B2:C3')
    page.locator('[data-action="copy"]').click()
    goto('F2')
    page.locator('[data-action="paste"]').click()
    check('Internal clipboard fallback preserves rectangular values', val(1,5)==2 and val(2,6)==20)
    goto('D2')
    page.locator('[data-action="copy"]').click()
    goto('H2')
    page.locator('[data-action="paste"]').click()
    check('Internal formula copy translates references', page.evaluate('gridline.sheet.raw(1,7)')=='=F2*G2' and val(1,7)==20)
    goto('A1:D1')
    page.locator('[data-action="bold"]').click()
    check('Ribbon formatting applies to the selection', page.evaluate('[0,1,2,3].every(c=>gridline.sheet.get(0,c).style.bold)'))
    page.locator('.sheet-tab.selected').dblclick()
    page.locator('#sheet-name-input').fill('Browser test')
    page.locator('#sheet-rename-apply').click()
    check('Worksheet rename dialog updates model and tab', page.evaluate('gridline.sheet.name')=='Browser test' and page.locator('.sheet-tab.selected').inner_text()=='Browser test')
    goto('B2')
    page.locator('[data-tab="View"]').click()
    page.locator('[data-action="freeze"]').click()
    check('Freeze panes uses active row and column', page.evaluate('gridline.sheet.freezeRows===1 && gridline.sheet.freezeCols===1'))
    page.locator('[data-tab="Review"]').click()
    page.locator('[data-action="add-note"]').click()
    page.locator('#note-text').fill('Browser test note: local-only annotation.')
    page.locator('#note-save').click()
    check('Cell notes persist into the model and panel', page.evaluate('gridline.sheet.get(1,1).note')=='Browser test note: local-only annotation.' and page.locator('.note-card').count()==1)
    page.locator('[data-action="close-panel"]').click()
    page.locator('[data-tab="Home"]').click()
    goto('A1:D3')
    page.locator('[data-tab="Data"]').click()
    page.locator('[data-action="sort-desc"]').click()
    check('Sorting preserves header and reorders data rows', val(0,0)=='Item' and val(1,0)=='Beta' and val(2,0)=='Alpha')
    goto('A1:D3')
    page.locator('[data-action="filter"]').click()
    page.locator('.filter-values label').filter(has_text='Alpha').locator('input').uncheck()
    page.locator('#filter-apply').click()
    check('Value filters hide nonmatching rows', page.evaluate('gridline.sheet.hiddenRows.size')==1)
    page.locator('[data-action="clear-filter"]').click()
    check('Clear filters restores visibility', page.evaluate('gridline.sheet.hiddenRows.size')==0)
    page.locator('[data-tab="Home"]').click()
    page.locator('[data-action="find"]').click()
    page.locator('#find-query').fill('Alpha')
    page.locator('#replace-query').fill('Gamma')
    page.locator('#replace-all').click()
    check('Find and replace edits matching cells', val(2,0)=='Gamma')
    page.locator('[data-action="close-panel"]').click()
    # Verify actual XML parsing, all formulas, styles, dimensions and workbook names.
    roundtrip = page.evaluate('''async()=>{const original=Gridline.createSampleWorkbook();const bytes=Gridline.exportXLSX(original);const {workbook:restored,warnings}=await Gridline.importXLSX(bytes,'Roundtrip');let mismatches=[];for(let i=0;i<original.sheets.length;i++){const a=original.sheets[i],b=restored.sheets[i];for(const [key,cell]of a.cells){if(!cell.raw)continue;const[r,c]=key.split(',').map(Number);const av=original.value(a,r,c),bv=restored.value(b,r,c);if(String(av)!==String(bv))mismatches.push(a.name+'!'+key+': '+av+' != '+bv);}}return {bytes:bytes.length,sheets:restored.sheets.length,mismatches,mergeCount:restored.sheets[0].merges.length,originalMerges:original.sheets[0].merges.length,freeze:restored.sheets[1].freezeRows,name:restored.names.COST_RATIO,style:restored.sheets[0].get(1,1).style,columns:restored.sheets[0].colWidths.size,warnings};}''')
    check('XLSX export/import round-trip preserves calculated values', roundtrip['sheets']==3 and not roundtrip['mismatches'], roundtrip)
    check('XLSX round-trip preserves basic workbook structures', roundtrip['mergeCount']==roundtrip['originalMerges'] and roundtrip['freeze']==1 and roundtrip['name'] and roundtrip['columns']>0)
    encoded = page.evaluate("btoa(Array.from(Gridline.exportXLSX(Gridline.createSampleWorkbook()),v=>String.fromCharCode(v)).join(''))")
    original_zip = zipfile.ZipFile(io.BytesIO(base64.b64decode(encoded)))
    def repack(date1904=False):
        output = io.BytesIO()
        with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as z:
            for name in original_zip.namelist():
                data = original_zip.read(name)
                if date1904 and name=='xl/workbook.xml':
                    data=data.replace(b'<sheets>',b'<workbookPr date1904="1"/><sheets>')
                z.writestr(name, data)
        return base64.b64encode(output.getvalue()).decode()
    compressed = page.evaluate("async b=>{const {workbook:w}=await Gridline.importXLSX(Uint8Array.from(atob(b),c=>c.charCodeAt(0)));return w.value(w.sheets[0],5,1);}", repack())
    check('Native DEFLATE decompression imports a compressed XLSX', compressed==2187000)
    rejection = page.evaluate("async b=>{try{await Gridline.importXLSX(Uint8Array.from(atob(b),c=>c.charCodeAt(0)));return '';}catch(e){return e.message;}}", repack(True))
    check('Unsupported 1904 date-system files are rejected explicitly', '1904' in rejection)
    page.wait_for_timeout(800)
    check('Autosave writes a restorable workbook snapshot to Storage interface', page.evaluate("Gridline.Workbook.fromJSON(JSON.parse(localStorage.getItem('gridline.workbook.v1'))).sheets.length") == 4)
    page.locator('[data-action="performance"]').click()
    start = time.perf_counter()
    page.locator('#perf-test').click()
    elapsed = (time.perf_counter()-start)*1000
    check('Stress sheet creates 80,008 sparse cells', page.evaluate('gridline.sheet.cells.size')==80008, {'wall_ms':round(elapsed,2)})
    page.locator('[data-action="close-panel"]').click()
    goto('D10001')
    page.wait_for_timeout(200)
    check('Virtualized scrolling reaches row 10,001 with correct formulas', val(10000,3)==50 and val(10000,7)==5, {'revenue':val(10000,3),'contribution':val(10000,7)})
    metrics = page.evaluate('({visibleCells:gridline.renderer.visibleCellCount,lastFrameCPUms:gridline.renderer.lastFrameMs,storedCells:gridline.sheet.cells.size,active:gridline.active})')
    check('Stress view renders only its viewport', metrics['visibleCells']<2000, metrics)
    page.locator('[data-action="theme"]').click()
    check('Theme toggle updates renderer state', page.evaluate('gridline.renderer.dark') is True)
    page.locator('[data-action="zoom-in"]').click()
    check('Zoom command updates the viewport transform', abs(page.evaluate('gridline.renderer.zoom')-1.1)<1e-9)
    check('Browser interactions produce no uncaught JavaScript errors', not errors, errors)
    report={'harness':'served origin' if args.url else 'inline opaque origin, in-memory Storage fixture','browser':browser.version,'backend':backend,'passed':len(checks),'checks':checks,'stressMetrics':metrics,'uncaughtErrors':errors,'notes':['GPU execution is verified only when backend is webgpu.','CPU frame measurement is not GPU completion time or a cross-machine benchmark.','In-memory storage fixture does not validate real browser persistence.']}
    (ROOT/'docs/browser-test-results.json').write_text(json.dumps(report,indent=2))
    print(json.dumps({'passed':len(checks),'backend':backend,'stress':metrics},indent=2))
    browser.close()
